### PR TITLE
Optional v2 storage

### PR DESCRIPTION
**Pull request by mwhudson**
Add a way to turn on more interesting gaps behaviour on the command line, and enable deleting preserved partitions in that mode. I think this approach has legs, it lets us break everything in the new world while not worrying about breaking existing behaviour. With a finished version of [dbungert:offsets-and-stretchy](https://github.com/dbungert/subiquity/tree/offsets-and-stretchy) merged in it might not even result in completely mad behaviour!

### CODE REVIEW

**Comment by dbungert** [comment]
So far so good.  I really like the feature flag argument.

**Comment by mwhudson** [comment]
This is now just the absolute minimal version.

**Comment by mwhudson** [comment]
Scratch that, I put the more interesting parts_and_gaps back because that's really fundamental to everything else.

**Review by dbungert — APPROVED** [review]
LGTM.
As an additional test, I experimented with the API tests set for storage version 2.  All tests pass except for test_v2_flow, which also passes if I update it to not assume a certain order for objects in the partitions array and lookup partitions by their number.

**Pull request merged**
