### PR TITLE
do not try to reuse a name of an existing vg in guided_lvm

### PR DESCRIPTION
**Pull request by mwhudson**
for https://bugs.launchpad.net/bugs/1905412

### CODE REVIEW

**Comment by mwhudson** [comment]
Haven't tested this at all yet!

**Comment by mwhudson** [comment]
I've now tested this a bit and it seems to work. Will test it again tomorrow after a nice fresh cup of coffee (unless someone beats me to it)

**Review by dbungert — APPROVED** [review]
LGTM

**Comment by dbungert** [comment]
I did a test of this as well and it seems fine.  My test was to run a sample install in kvm, create a second disk, run install a second time hitting that second disk, and then boot it and analyze the actual VGs present.  In this configuration the system booted the first install but can see both VGs.

**Comment by mwhudson** [comment]
Thanks for testing!

**Pull request merged**
