### PR TITLE
write any wifi config to a file only readable by root

### PR DESCRIPTION
**Pull request by mwhudson**
Perhaps a bit trivial for a PR to itself but oh well.

### CODE REVIEW

**Review by dbungert — CHANGES_REQUESTED** [review]
What about wired 802.1x?
Should we just 0600 the whole thing?

**Comment by mwhudson** [comment]
> What about wired 802.1x?

Hm on the one hand subiquity doesn't support this, on the other, yes, maybe we should be more generic here.

> Should we just 0600 the whole thing?

Or do that. I feel like it would be nice not to do this but I don't know if it's worth the effort.

**Review by dbungert — APPROVED** [review]
Given that wired 802.1x is not supported yet, downgrading my change request to an eventual suggestion.

**Comment by mwhudson** [comment]
Thanks. I'll add a comment about that.

**Pull request merged**
