### PR TITLE
Kinetic merge 2022-09-28

### PR DESCRIPTION
**Pull request by dbungert**
* cherry-picked c063717..aff9ed0a from #1430 for LP: #[1987341](http://pad.lv/1987341)
* cherry-picked ecb6cb6 from #1418 for LP: #[1988407](http://pad.lv/1988407)
* cherry-picked 83a7aff from #1425
* cherry-picked b9f9aee from #1419 for LP: #[1980584](http://pad.lv/1980584)
* cherry-picked 5c636ac..9d5ae67 from #1426 for LP: #[1989193](http://pad.lv/1989193) and LP: #[1989198](http://pad.lv/1989198)
* cherry-picked 884f296 from #1428 for LP: #[1989353](http://pad.lv/1989353)

### CODE REVIEW

**Review by mwhudson — APPROVED** [review]

**Comment by mwhudson** [comment]
This all looks fine, I didn't scan main for other things we might want to include fwiw.

**Comment by ogayot** [comment]
LGTM. I think we also want to include at least #1411 but did not do a full scan of main either.

**Comment by frank-heimes** [comment]
Would it be possible to get this
https://git.launchpad.net/curtin/commit/?id=f174ed73
in as well?

**Comment by dbungert** [comment]
@ogayot @frank-heimes - those both sound like good fixes to include, I will look at those for the next merge

**Pull request merged**
