### PR TITLE
source: add a default value for search_drivers in POST /source

### PR DESCRIPTION
**Pull request by ogayot**
For backward compatibility reasons with the desktop installer implementation, we now provide a default value (i.e., `false`) for the new `search_drivers` parameter in `/source`.

CC @jpnurmi

### CODE REVIEW

**Review by dbungert — CHANGES_REQUESTED** [review]
Running this through quick api test, the argument is still required.
```
  File "./v2", line 152, in auto_server_install
    await inst.post('/source', source_id='ubuntu-server')
  File "./v2", line 83, in post
    return await self.request('POST', query, data, **kwargs)
  File "./v2", line 110, in request
    raise ClientException(content)
__main__.ClientException: Traceback (most recent call last):
  File "/home/dbungert/dev/github/canonical/subiquity/subiquity/common/api/server.py", line 115, in handler
    raise TypeError(
TypeError: missing required argument "search_drivers"
```

**Comment by ogayot** [comment]
> Running this through quick api test, the argument is still required.
> 
> ```
>   File "./v2", line 152, in auto_server_install
>     await inst.post('/source', source_id='ubuntu-server')
>   File "./v2", line 83, in post
>     return await self.request('POST', query, data, **kwargs)
>   File "./v2", line 110, in request
>     raise ClientException(content)
> __main__.ClientException: Traceback (most recent call last):
>   File "/home/dbungert/dev/github/canonical/subiquity/subiquity/common/api/server.py", line 115, in handler
>     raise TypeError(
> TypeError: missing required argument "search_drivers"
> ```

Well, that does not sound right :( The following command succeeds and does what it should do.

```
$ curl --unix-socket .subiquity/socket -X POST http://a/source'?source_id="ubuntu-server"'
```
I'm investigating.

**Review by dbungert — APPROVED** [review]
Sorry, false alarm, my test was invalid.

**Comment by ogayot** [comment]
> Sorry, false alarm, my test was invalid.

No problem. I took the opportunity to add tests for it following your comment.

**Review by dbungert — APPROVED** [review]
Thanks!

**Comment by mwhudson** [comment]
Thanks from me too

**Pull request merged**
