### PR TITLE
Add docs checks to GH workflows

### PR DESCRIPTION
**Pull request by rkratky**
This adds the following automated docs checks to GH Actions:
  * spellcheck
  * linkcheck
  * inclusive-language check

(Fixes [FR-5662](https://warthogs.atlassian.net/browse/FR-5662))

[FR-5662]: https://warthogs.atlassian.net/browse/FR-5662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by rkratky** [comment]
I fixed the invocation of the test (inclusive lang.) that failed to run, and it's now running and passing.

The last failing test is spellcheck, which is fixed by #1847 (when that PR is merged, the spellcheck should be passing).

**Review by dbungert — APPROVED** [review]

**Review by dbungert — APPROVED** [review]

**Comment by dbungert** [comment]
I am cancelling and restarting the stuck jobs.

**Comment by dbungert** [comment]
The spelling check failed on 2 items, however they don't fail when run locally.  I presume there is a slight difference in the dictionaries between the two test run cases.

I have pushed a commit with proposed fixes for these, please incorporate or re-implement as you see fit, @rkratky .

**Comment by rkratky** [comment]
Thanks, @dbungert. Merging with your commit as is.

(Though I cannot fathom what dictionary could exclude 'boolean'... And for 'runtime', most style guides allow for both forms ('runtime' and 'run time'), so I'll add it to the wordlist in the next iteration, too.)

**Pull request merged**
