### PR TITLE
Support LUKS with 'lvm' autoinstall storage layout

### PR DESCRIPTION
**Pull request by rmounce**
To support the same behaviour that was available with d-i/preseed.

### CODE REVIEW

**Comment by dbungert** [comment]
```
2023-03-01 23:40:50,231 DEBUG root:37 finish: subiquity/Filesystem/guided_POST: SUCCESS: 500 Traceback (most recent call last):                                                                                                         
  File "/home/dbungert/dev/github/canonica...                                                                       
2023-03-01 23:40:50,231 DEBUG subiquity.server.server:456 request to /storage/guided crashed                        Traceback (most recent call last):                                                                                  
  File "/home/dbungert/dev/github/canonical/subiquity/subiquity/common/api/server.py", line 134, in handler         
    result = await implementation(**args)                                                                           
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                           
  File "/home/dbungert/dev/github/canonical/subiquity/subiquity/server/controllers/filesystem.py", line 604, in guided_POST                                                                                                             
    self.guided(GuidedChoiceV2.from_guided_choice(data))                                                            
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                             
  File "/home/dbungert/dev/github/canonical/subiquity/subiquity/common/types.py", line 447, in from_guided_choice   
    use_all_space=choice.use_all_space,                                                                             
                  ^^^^^^^^^^^^^^^^^^^^                                                                              
AttributeError: 'GuidedChoice' object has no attribute 'use_all_space'                                              
```

**Comment by dbungert** [comment]
`make install_deps lint check` can help if you want to run it locally.  Beware that's going to install a bunch of things.

**Comment by rmounce** [comment]
> `make install_deps lint check` can help if you want to run it locally. Beware that's going to install a bunch of things.

Thanks, sorry for the CI spam. I've now signed the CLA so not sure if that needs manual review by legal, DB still needs to sync or what I'm missing there.

Had a quick look at the tests in `subiquity/server/controllers/tests/test_filesystem.py`. Maybe it's going right over my head, I can't see any existing tests that could be spliced together to check:
- Whether LUKS is being used
- The sizing of a LV within a PV

Looks like the existing test suite passes for just my first commit which is trivially exposing the existing GUI LUKS option via autoinstall. Are you happy with the approach for this bit?

I'm inclined to open a separate PR for the `use_all_space` bit once it's passing tests.

**Comment by dbungert** [comment]
> I've now signed the CLA so not sure if that needs manual review by legal, DB still needs to sync or what I'm missing there.

Yea, I'm sure that'll sort itself out in a day.

So I ran this branch through an autoinstall, with the following as input:
```
version: 1
identity:
    hostname: ai-test
    password: "$y$j9T$UdY22v4Kexn/AZcIzBSUc0$2DnuvWDSwoDCFPlbk1ghZeT2qFrEBKY1bpFQoexHdw7"
    username: ubuntu
storage:
    layout:
        name: lvm
        password: passw0rd
```

Then grepped the output.  It would be best if we didn't log the contents of storage.layout.password, looks like there are 3 places that do so.

```
58:2023-03-02 03:11:53,211 DEBUG subiquity.server.controllers.filesystem:161 load_autoinstall_data {'layout': {'name': 'lvm', 'password': 'passw0rd'}}
59:2023-03-02 03:11:53,211 DEBUG subiquity.server.controllers.filesystem:162 self.ai_data = {'layout': {'name': 'lvm', 'password': 'passw0rd'}}
236:2023-03-02 03:11:53,639 DEBUG subiquity.server.controllers.filesystem:925 self.ai_data = {'layout': {'name': 'lvm', 'password': 'passw0rd'}}
```

Just remove those log statements for now and I'm good to land this.

**Review by dbungert — APPROVED** [review]
This is all fine but github's action runners are throwing some error I've never seen before, I'd prefer to let them settle first.

**Comment by dbungert** [comment]
Thank you!

**Pull request merged**
