### PR TITLE
tidy up examples/ directory

### PR DESCRIPTION
**Pull request by mwhudson**
Move machine configs, sources, autoinstall files and dry-run configs into their own subdirectories.

### CODE REVIEW

**Comment by mwhudson** [comment]
This is obviously very important!!

**Comment by ogayot** [comment]
Thanks for doing some cleanup. Should we remove the `source`, `answers`, `autoinstall`, `dr-cfg` from the filenames now that they're in the relevant directories?

**Comment by mwhudson** [comment]
yes i think that looks better.

**Review by ogayot — APPROVED** [review]
Thanks!

**Pull request merged**
