### PR TITLE
Add --use-fuse switch to kvm-test --install so it can run as non-root

### PR DESCRIPTION
**Pull request by ogayot**
Passing `--use-fuse` to `scripts/kvm-test.py --install` allows to run as non-root.

It requires installation of the package fuseiso so the switch is disabled by default.

Signed-off-by: Olivier Gayot <olivier.gayot@canonical.com>

### CODE REVIEW

**Review by dbungert — CHANGES_REQUESTED** [review]
I love the idea so much I want it to be the default and not an option.
Would you add fuse / fuseiso to the packages installed in `make aptdeps`?

**Comment by mwhudson** [comment]
Would you be able to do something similar for https://github.com/mwhudson/livefs-editor? :)

**Comment by ogayot** [comment]
> I love the idea so much I want it to be the default and not an option. Would you add fuse / fuseiso to the packages installed in `make aptdeps`?

sure thing :)

> Would you be able to do something similar for https://github.com/mwhudson/livefs-editor? :)

I can give it a try !

**Review by dbungert — APPROVED** [review]

**Comment by dbungert** [comment]
Great idea, thanks!  It bugged me to need sudo in this script and I now have hope that we can make it not need root at all.

**Pull request merged**
