### PR TITLE
enforce code format with black + isort

### PR DESCRIPTION
**Pull request by dbungert**
* CI now requires that the code is already formatted with black and isort
* local reformatting can be done with 'make format' or 'make black' or 'make isort'.  tox.ini has been overhauled to remove the unusable environments (all of them) and add black and isort environments.  tox and the workflow are using the same version selectors.
* using tox also required bdist_wheel to be working, so also fix that
* appropriate configs are in place so that the tools (black, isort, flake8) should be playing nice with each other
* pre-commit hooks added, to incrementally run the format steps and fail the commit if not formatted

Suggestion for reviewing this PR:
* the source directories are going to be filled with reformatted code.  The bulk of the changes to set this up have been structured before the reformat commit, then the reformat is applied, then the workflow is enabled and .git-blame-ignore-revs is populated.
* a few source directories have interesting changes that are not generated by the code formatting tools - these have a "fix lint" note in the commit summary, and these commits are before the reformat.  These changes are about fixing things that black would otherwise reformat in a way that would trigger flake8 failure.
* a supplemental commit to fix joining of long lines has been added, after the format commit, by temporarily using `black --experimental-string-processing`

### CODE REVIEW

**Review by ogayot — CHANGES_REQUESTED** [review]
I have mixed feelings on this one. This is affecting the entire tree - and therefore will make all existing PRs obsolete. When I see some of the changes (e.g., https://github.com/canonical/subiquity/pull/1738/files#diff-dc9f10a528237b402741453879a9e45cc48cbc8a9d4ce289c096b41f649bb895), it doesn't necessarily feel like an improvement IMO. Can we somehow relax this by making only new code affected ?

If we are headed this direction, I would like the extra quoting in merged multi-line strings to be dropped, e.g.:

"Select one of available recovery systems and a desired " "action to execute."

If you search `" "` in the code, you will find plenty of occurrences.

**Comment by mwhudson** [comment]
As you know I'm in favour of this (I expect existing PRs can be un-obsoleted by running black on them first). I agree that the joined lines are strange and should be fixed.

**Comment by mwhudson** [comment]
Oh yeah, would it be possible to add something to CONTRIBUTING.md about how to add a pre-commit hook to enforce this? I guess I'll want something for emacs too but I'm sure I can figure that out on my own :-)

**Comment by dbungert** [comment]
> If we are headed this direction, I would like the extra quoting in merged multi-line strings to be dropped, e.g.:
> 
> "Select one of available recovery systems and a desired " "action to execute."

Yes, those are pretty ugly.
The `--experimental-string-processing` option is around this problem.  AIUI, that wouldn't be a [mainline feature](https://www.github.com/psf/black/issues/2188) until v24 (unless it misses the window.)

**Comment by dbungert** [comment]
Marking draft as this requires a rebase before merge.  It is otherwise reviewable.

**Comment by dbungert** [comment]
(I don't want to enable preview features generally, just using that for testing purposes)

**Comment by dbungert** [comment]
> Oh yeah, would it be possible to add something to CONTRIBUTING.md about how to add a pre-commit hook to enforce this?

Thanks for the excuse to learn more about these - done!

**Comment by dbungert** [comment]
> > If we are headed this direction, I would like the extra quoting in merged multi-line strings to be dropped, e.g.:
> > "Select one of available recovery systems and a desired " "action to execute."
> 
> Yes, those are pretty ugly. The `--experimental-string-processing` option is around this problem. AIUI, that wouldn't be a [mainline feature](https://www.github.com/psf/black/issues/2188) until v24 (unless it misses the window.)

These are now fixed in a follow-up format commit.

**Review by ogayot — APPROVED** [review]
Thanks!

**Review by mwhudson — APPROVED** [review]
Let's get this done

**Pull request merged**
