### PR TITLE
snapcraft: remove dupe jsonschema

### PR DESCRIPTION
**Pull request by dbungert**

### CODE REVIEW

**Review by blackboxsw — APPROVED** [review]
* cherry-picked this into #1359  which represented tracebacks w/ cloud-init due to lack of support of pip installed jsonschema version 2.6.0 on receiving any valid or invalid `autoinstall.yaml`
## terminal 1
```

$ mkdir /tmp/autoinstall; cd /tmp/autoinstall

$ cat > /tmp/autoinstall/user-data.VALID <<EOF
#cloud-config
# Valid cloud-config in autoinstall.user-data specifying correct list value for ssh_import_id
autoinstall:
    version: 1
    identity:
        hostname: ai-test
        password: "/2.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
        username: ubuntu
    user-data:
        ssh_import_id: [chad.smith]
EOF

$ cat > /tmp/autoinstall/user-data.INVALID <<EOF
#cloud-config
# Valid cloud-config in autoinstall.user-data specifying correct list value for ssh_import_id
autoinstall:
    version: 1
    identity:
        hostname: ai-test
        password: "/2.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
        username: ubuntu
    user-data:
        ssh_import_id: NOTALIST
EOF


$ sudo python3 -m http.server 3003
Serving HTTP on 0.0.0.0 port 3003 (http://0.0.0.0:3003/) ...
```
## terminal 2
```
$ snapcraft snap --output subiquity_test.snap
$ isoname=kinetic-live-server-amd64.iso
$ sudo ./scripts/inject-subiquity-snap.sh ${isoname} subiquity_test.snap custom.iso
$ qemu-img create -f raw target.img 10G
```
 ### test 1: invalid schema raises a cloudinit SchemaError from the right place, no traces in other `jsonschema.validate` calls
```
$ cp /tmp/autoinstall/user-data.INVALID /tmp/autoinstall/user-data
$ kvm -no-reboot -m 1024     -drive file=target.img,format=raw,cache=none,if=virtio     -cdrom ~/src/subiquity/custom.iso     -kernel /mnt/casper/vmlinuz     -initrd /mnt/casper/initrd     -append 'autoinstall ds=nocloud-net;s=http://_gateway:3003/'
```
 CORRECT ERROR from test1 autoinstall logs:
```
2022-08-25 20:55:03,512 ERROR root:37 finish: subiquity/Userdata/load_autoinstall_data: FAIL: Cloud config schema errors: autoinstall.user-data.ssh_import_id: 'NOTALIST' is not of type 'array'
```
### validate installed jsonschema in snap environment after the correct invalid schema error above

```
+ echo DEBUG: Ensure only one copy of jsonschema visible to subiquity
DEBUG: Ensure only one copy of jsonschema visible to subiquity
+ grep jsonschema/validators.py
+ find /snap/subiquity/x1
/snap/subiquity/x1/usr/lib/python3/dist-packages/jsonschema/validators.py
+ echo DEBUG: check version of jsonschema
DEBUG: check version of jsonschema
+ PYTHONPATH=/snap/subiquity/x1/usr/lib/python3/dist-packages
+ python3 -c 'import jsonschema; print(jsonschema.__version__)'
3.2.0
```

### test 2: test valid_subschema: no jsonschema.validation errors from any curtin/filesystem controllers/components due to cloudinit creating it's own Draft4SchemaValiditor
```
$ cp /tmp/autoinstall/user-data.VALID /tmp/autoinstall/user-data
$ kvm -no-reboot -m 1024     -drive file=target.img,format=raw,cache=none,if=virtio     -cdrom ~/src/subiquity/custom.iso     -kernel /mnt/casper/vmlinuz     -initrd /mnt/casper/initrd     -append 'autoinstall ds=nocloud-net;s=http://_gateway:3003/'

...#  autoinstall completes without error and shuts down the vm
$ kvm -m 1024 -hda target.img -serial stdio
# sudo cloud-init status --wait --long shows no errors on booted target.img
```

**Review by mwhudson — APPROVED** [review]
If it works in a VM ship it :)

**Comment by dbungert** [comment]
Bleh, I found an unrelated problem.  I will send a fix PR tomorrow along with tests and clean this up.

**Comment by dbungert** [comment]
VM test of this, cherry-picked onto a branch that isn't baseline broken, works just fine.
Merging.
See https://github.com/canonical/subiquity/pull/1404 for the baseline fix.

**Pull request merged**
