### PR TITLE
Fix wrong indent of another volume install doc

### PR DESCRIPTION
**Pull request by aim-nara**

### CODE REVIEW

**Comment by Chris-Peterson444** [comment]
Hi @aim-nara thanks for your contribution and nice catch! This looks good to me, but we'll have to get CI happy before we can merge. Have you signed the CLA? We've had issues in the past with the CLA bot but I believe that's been sorted now.

**Comment by aim-nara** [comment]
@Chris-Peterson444 Thank you for reviewing. I've signed to https://ubuntu.com/legal/contributors/agreement as an individual contributor.

**Comment by Chris-Peterson444** [comment]
Looks like there may still be trouble with the CI bot. Could you confirm for me that you signed using your github username? Alternatively, if you signed with your launchpad account you can change the committer email address to the one associated with your launchpad account and that should work.

**Comment by aim-nara** [comment]
@Chris-Peterson444 Thank you for running the workflow again
I've changed email of https://github.com/canonical/subiquity/pull/2012 and re-signed the CLA. Could you check the new PR?

**Pull request closed without merging**
