### PR TITLE
redo how install variant determines which models to wait for

### PR DESCRIPTION
**Pull request by mwhudson**
This is probably a bit overkill, but the thrust here is to allow the source variant (i.e. desktop or server) to change more than once. This isn't going to happen for a long time obviously but I wanted to clean this up sooner rather than later. There are ways this could be made still more general of course, but well. I think this is OK.

### CODE REVIEW

**Review by dbungert — APPROVED** [review]
LGTM

**Comment by dbungert** [comment]
FYI if we land this before WSL, there will be some nasty merge conflicts waiting for that branch.

**Comment by mwhudson** [comment]
I really need to make time to digest that work :/ I think possibly this can wait until after we make a release for 20.04.3 too, it's a bit risky and brings no immediate benefit.

**Comment by mwhudson** [comment]
Going to merge this now that we did a stable release and the world didn't explode.

**Pull request merged**
