### PR TITLE
remove special cases around mounting/unmounting /target/cdrom

### PR DESCRIPTION
**Pull request by mwhudson**

### CODE REVIEW

**Comment by mwhudson** [comment]
I haven't vmtested this yet and after what happened last time I definitely should!

**Comment by ogayot** [comment]
LGTM, thanks!

**Review by ogayot — APPROVED** [review]

**Review by dbungert — APPROVED** [review]
I won't block merge for this, but if you have thoughts on how we might automatically test this, given that we've been bit by this before, that would be nice.

On the other hand I want to see some level of VM testing in CI, so maybe that's the answer.

**Comment by mwhudson** [comment]
Yes, I think some kind of automated VM testing for PRs is the right answer here. If you can make that happen, I'll be very happy!

**Comment by mwhudson** [comment]
finally managed to test this in a vm

**Pull request merged**
