### PR TITLE
probert: update for python 3.10 fix (lp-1964571)

### PR DESCRIPTION
**Pull request by dbungert**

### CODE REVIEW

**Review by mwhudson — APPROVED** [review]
Do we want to merge this to server/jammy too? Or create a server/jammy branch for probert and cherry pick things into that?

**Comment by dbungert** [comment]
My hunch for probert is that 100% of the things that land there in the next monthish are stuff we want for Jammy, so I lean towards leaving it alone and just pulling from main.
If we find ourselves landing some feature we can do a branch on probert, and if that day comes it shouldn't require touching subiquity at all since we pick up probert by a fixed commit (which could be on any branch).
What do you think?

**Comment by dbungert** [comment]
therefore I would want to merge this PR to the subiquity server/jammy branch.

**Comment by mwhudson** [comment]
:+1: -- my only hesitation is: does the probert referenced by the server/jammy branch invoke os-prober?

**Comment by dbungert** [comment]
It does and we don't need it to.  It would be safer to back out the os-prober call (I saw an os-prober looking failure in one of Heinrich's logs)
New proposal:
1) Merge this as is
2) create probert stable branch
3) Change the probert stable branch to not include a call to os-prober
4) merge to server/jammy that resulting probert commit

**Comment by mwhudson** [comment]
That all sounds good to me!

**Pull request merged**
