### PR TITLE
Fix storage 'path' matcher doc & add new matchers to do what 'path' claimed to

### PR DESCRIPTION
**Pull request by rmounce**

### CODE REVIEW

**Comment by rmounce** [comment]
Hi @dbungert

Sorry to tag directly, but you've been kind enough to review my others PRs. I think this one's comparatively trivial & addresses an error in the docs that's affecting multiple users.

My selfish motivation to push this forward is that this is the final issue preventing us from using unpatched live-server .iso's. Happy to rework if necessary.

Thanks,
Ryan

**Comment by dbungert** [comment]
> Sorry to tag directly, but you've been kind enough to review my others PRs

No problem, thank you for the contributions.  I meant to get this sorted out before Lunar was done but things got busy.

I'd like some unit tests for this sort of thing.  There are some similar tests in subiquity/models/tests/test_filesystem.py that you can use as an example.

> My selfish motivation to push this forward is that this is the final issue preventing us from using unpatched live-server .iso's

Once this is merged, doing a `refresh-installer: {update: yes, channel: edge}` should let you verify, and we can sort out stable branch merges from there.

**Comment by rmounce** [comment]
Fair enough, unit tests added. I can't figure out how to run them though and/or whether CI runs them.

**Review by dbungert — APPROVED** [review]

**Comment by dbungert** [comment]
Had the chance to vm test all these today, working nicely.  Thanks.

**Comment by dbungert** [comment]
The build for this can now be found on the edge channel, so an autoinstall like shown above should pick up these changes.

**Pull request merged**
