### PR TITLE
Fix advancing from snap list screen before snaps have loaded

### PR DESCRIPTION
**Pull request by lambda-propaganda**
when done() is called before the snap has loaded this causes an attribute error on the following line

'log.debug("snaps to install %s", self.selections_by_name)'

### CODE REVIEW

**Comment by lambda-propaganda** [comment]
Sorry was in quite a rush when I was submitting the PR. I've had issues running the installer in an air gapped network. The issue is if the connection to the snapstore was still pending when the submit button was pressed, the variable 'selections_by_name' attribute had not been created yet causing the installation to crash with an AttributeError. 

This PR just adds a better error message, I'm not able to test the change as I made the PR through the web browser.

**Comment by dbungert** [comment]
This is a step in the right direction but not quite correct.
Upon testing this, without the change I can see the crash, but with it we get stuck in a loop that also can produce a crash.

**Review by dbungert — CHANGES_REQUESTED** [review]
See comment -  the change isn't quite enough to fix.

**Comment by dbungert** [comment]
@lambda-propaganda - are you interested in pursuing this further, or should we take it from here?  I didn't want to interrupt if you were looking to continue on this, but at the same rate this is pretty nasty for offline users and I'd like to see it resolved.

**Comment by lambda-propaganda** [comment]
Hi Sorry for the delay, feel free to take over. I discovered this bug in an offline environment, so it makes submitting a PR very difficult as I have to do it through the web browser on another machine.

**Review by dbungert — APPROVED** [review]
Marking approve because it looks deceptive otherwise in the list.
@mwhudson - please review, should be trivial

**Review by mwhudson — APPROVED** [review]

**Pull request merged**
