### PR TITLE
subiquity.common.serialize: add a way to have a "non-exhaustive" enum

### PR DESCRIPTION
**Pull request by mwhudson**
relates to #1980

### CODE REVIEW

**Review by dbungert — APPROVED** [review]
Thanks!

Looks fine, one open question, and a rebase to cleanup commits please.

**Comment by mwhudson** [comment]
I rebased and cleaned up one bit of logic to hopefully more comprehensible. I don't see the open question though?

**Review by dbungert — APPROVED** [review]
Uh, I think I confused this with the other PR where I was suggesting to document one more possible state in the enum.  LGTM, thanks!

**Comment by mwhudson** [comment]
I should tag @d-loose so he knows about the change in capabilities of the API here -- basically a dict with enum keys is serialized as an object, not a list of key, value pairs. there are no such types in the subiquity API today though.

**Pull request merged**
